AWSTemplateFormatVersion: 2010-09-09
Description: Certificate

Parameters:
  ProjectName:
    Type: String
    Description: The name of the project.
  DomainName:
    Type: String
    Description: The domain name of the project.
  HostedZoneId:
    Type: String
    Description: The hosted zone id of the domain.

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags: [{ Key: Project, Value: !Ref ProjectName }]
    
Outputs:
  CertificateArn:
    Description: Arn of the certificate
    Value: !Ref Certificate 