AWSTemplateFormatVersion: "2010-09-09"
Description: "Certificate"

Parameters:
  ProjectName:
    Type: String
    Description: "The name of the project. USE KEBAB-CASE ONLY."
  DomainName:
    Type: String
    Description: "The domain name of the project."
  HostedZoneId:
    Type: String
    Description: "The hosted zone id of the domain."

Resources:
  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: "DNS"
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags: [{ Key: "Project", Value: !Ref ProjectName }]
    
Outputs:
  CertificateArn:
    Description: "Arn of the certificate"
    Value: !Ref Certificate 
    Export:
      Name: !Sub "${ProjectName}-CertificateArn"
  
  DomainName:
    Description: "DomainName you entered."
    Value: !Ref DomainName
    Export:
      Name: !Sub "${ProjectName}-DomainName"

  HostedZoneId:
    Description: "HostedZoneId name you entered."
    Value: !Ref HostedZoneId
    Export:
      Name: !Sub "${ProjectName}-HostedZoneId"
